Repository vrk-kpa/suomifi-design-system, pull requests merged in 2020-09, with the labels that each got.

#439 [Fix] Textarea and textinput content keys
  locale/af/textarea.json
  locale/en/textarea.json
  locale/fi/textarea.json
  src/pages/components/textarea.tsx
  src/pages/components/textinput.tsx
Labels: bug

#440 [Feature] Upgrade all dependencies according to scope.
  yarn.lock
Labels: dependencies

#444 [Release] 0.2.0
  package.json
Labels: release

#445 Update master to 0.2.0.
  .tx/config
  locale/af/radiobutton.json
  locale/af/textarea.json
  locale/en/radiobutton.json
  locale/en/textarea.json
  locale/fi/radiobutton.json
  locale/fi/textarea.json
  locale/fi/textinput.json
  package.json
  src/components/ExampleComponents.tsx
  src/config/sidenav/components.js
  src/pages/components/radiobutton.tsx
  src/pages/components/textarea.tsx
  yarn.lock
Labels: release
