Repository vrk-kpa/suomifi-design-system, pull requests merged in 2020-04, with the labels that each got.

#313 Update to 5px base design tokens.
  package.json
  src/components/Annotation.tsx
  src/components/BulletedList.tsx
  src/components/BypassLink.tsx
  src/components/ComponentCode.tsx
  src/components/ComponentDescription.tsx
  src/components/ComponentExample.tsx
  src/components/ContentBoxes.tsx
  src/components/Footer.tsx
  src/components/LanguageSwitcher.tsx
  src/components/Link.tsx
  src/components/LinkList.tsx
  src/components/MainContent.tsx
  src/components/MainMenuItem.tsx
  src/components/NavItem.tsx
  src/components/Navigation.tsx
  src/components/NoteBox.tsx
  src/components/NotificationBox.tsx
  src/components/Paragraph.tsx
  src/components/Section.tsx
  src/components/SideNav.tsx
  src/components/SideNavItem.tsx
  src/components/header.tsx
  src/examples/styles.js
  src/pages/accessibility-statement.tsx
  src/pages/components/button.tsx
  src/pages/components/expander.tsx
  src/pages/components/heading.tsx
  src/pages/components/icon.tsx
  src/pages/components/searchinput.tsx
  src/pages/components/textinput.tsx
  src/pages/styles/colors.tsx
  src/pages/styles/icons.tsx
  src/pages/styles/typography.tsx
  yarn.lock
Labels: dependencies, enhancement

#320 [Feature] Update and upgrade deps
  .eslintrc
  .stylelintrc.json
  DEVELOPMENT.md
  README.md
  package.json
  src/components/ComponentDescription.tsx
  src/components/ExampleComponentUtil.tsx
  src/components/Footer.tsx
  src/components/LanguageSwitcher.tsx
  src/components/Link.tsx
  src/components/MainMenu.tsx
  src/components/Navigation.tsx
  src/components/NotificationBox.tsx
  src/components/ResponsiveComponentsUtil.tsx
  src/components/SideNav.tsx
  src/components/header.tsx
  src/components/images/ButtonsMobileFI.tsx
  src/components/layout.tsx
  src/config/mainnav.js
  src/config/sidenav/components.js
  src/config/sidenav/info.js
  src/config/sidenav/styles.js
  src/pages/404.tsx
  src/pages/accessibility-statement.tsx
  src/pages/components/block.tsx
  src/pages/components/breadcrumb.tsx
  src/pages/components/button.tsx
  src/pages/components/dropdown.tsx
  src/pages/components/expander.tsx
  src/pages/components/heading.tsx
  src/pages/components/icon.tsx
  src/pages/components/index.tsx
  src/pages/components/languagemenu.tsx
  src/pages/components/link.tsx
  src/pages/components/searchinput.tsx
  src/pages/components/text.tsx
  src/pages/components/textinput.tsx
  src/pages/components/toggle.tsx
  src/pages/index.tsx
  src/pages/info/accessibility.tsx
  src/pages/info/designers.tsx
  src/pages/info/developers.tsx
  src/pages/info/index.tsx
  src/pages/styles/colors.tsx
  src/pages/styles/icons.tsx
  src/pages/styles/index.tsx
  src/pages/styles/typography.tsx
  yarn.lock
Labels: DX, dependencies

#321 [Feature]Update react-i18next, i18next + some other minor
  package.json
  src/components/ComponentDescription.tsx
  src/components/ContentBoxes.tsx
  src/components/Footer.tsx
  src/components/LanguageSwitcher.tsx
  src/components/Link.tsx
  src/components/MainMenu.tsx
  src/components/Navigation.tsx
  src/components/NotificationBox.tsx
  src/components/Section.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/seo.tsx
  src/pages/404.tsx
  src/pages/accessibility-statement.tsx
  src/pages/components/block.tsx
  src/pages/components/breadcrumb.tsx
  src/pages/components/button.tsx
  src/pages/components/dropdown.tsx
  src/pages/components/expander.tsx
  src/pages/components/heading.tsx
  src/pages/components/icon.tsx
  src/pages/components/index.tsx
  src/pages/components/languagemenu.tsx
  src/pages/components/link.tsx
  src/pages/components/searchinput.tsx
  src/pages/components/text.tsx
  src/pages/components/textinput.tsx
  src/pages/components/toggle.tsx
  src/pages/index.tsx
  src/pages/info/accessibility.tsx
  src/pages/info/designers.tsx
  src/pages/info/developers.tsx
  src/pages/info/index.tsx
  src/pages/styles/colors.tsx
  src/pages/styles/icons.tsx
  src/pages/styles/index.tsx
  src/pages/styles/typography.tsx
  yarn.lock
Labels: DX, dependencies

#322 [Feature] Improve the Toggle's texts
  locale/fi/toggle.json
Labels: enhancement

#324 [Feature] Input-variation of Toggle added
  locale/af/toggle.json
  locale/en/toggle.json
  locale/fi/toggle.json
  src/pages/components/toggle.tsx
Labels: enhancement

#334 [Fix] Skip link functionality
  src/components/MainContent.tsx
Labels: bug
