Repository vrk-kpa/suomifi-design-system, pull requests merged in 2020-06, with the labels that each got.

#380 [Feature] Add checkbox component page
  .tx/config
  locale/af/checkbox.json
  locale/fi/checkbox.json
  package.json
  src/components/ExampleComponents.tsx
  src/config/sidenav/components.js
  src/pages/components/checkbox.tsx
  yarn.lock
Labels: enhancement

#389 [Feature] CircleCi to use 'machine' instead of 'docker' as executor
  .circleci/config.yml
Labels: bug

#391 [Feature] Update suomifi-ui-components to 0.16.1
  package.json
  yarn.lock
Labels: dependencies

#398 Add 1.0 and semantic versioning info on developer page and frontpage
  locale/fi/developers.json
  locale/fi/home.json
Labels: enhancement

#399 [Improvement] Update ui-components to 0.17.0 and add new Dropdown page content
  locale/af/dropdown.json
  locale/en/dropdown.json
  locale/fi/dropdown.json
  package.json
  src/pages/components/dropdown.tsx
  yarn.lock
Labels: dependencies, enhancement
