Repository vrk-kpa/suomifi-design-system, pull requests merged in 2020-03, with the labels that each got.

#220 [Feature] Update suomifi-ui-components to 0.6.1
  package.json
  yarn.lock
Labels: dependencies

#225 [Bugfix] Fix bug in TextInput's translations and update text content to latest from Transifex
  locale/af/textinput.json
  locale/en/textinput.json
  locale/fi/accessibility-statement.json
  locale/fi/button.json
  locale/fi/styles.json
  locale/fi/textinput.json
  locale/fi/toggle.json
  locale/fi/typography.json
Labels: bug, enhancement

#229 [Fix] Fixes from 0.1.0 release
  locale/af/icon.json
  locale/en/icon.json
  locale/fi/button.json
  locale/fi/common.json
  locale/fi/icon.json
  package.json
  yarn.lock
Labels: enhancement

#230 Update suomifi-icons to 0.1.0
  .tx/config
  locale/af/icon.json
  locale/af/icons.json
  locale/af/static-icons.json
  locale/en/icon.json
  locale/en/icons.json
  locale/en/static-icons.json
  locale/fi/icon.json
  locale/fi/icons.json
  locale/fi/static-icons.json
  package.json
  src/components/ContentBoxes.tsx
  src/components/ExampleComponents.tsx
  src/config/sidenav/components.js
  src/config/sidenav/info.js
  src/config/sidenav/styles.js
  src/pages/components/icon.tsx
  src/pages/styles/icons.tsx
  yarn.lock
Labels: dependencies, enhancement

#224 [Feature] Add block component page
  .tx/config
  locale/af/block.json
  locale/en/block.json
  locale/fi/block.json
  src/components/ExampleComponents.tsx
  src/config/sidenav/components.js
  src/config/sidenav/styles.js
  src/pages/components/block.tsx
Labels: enhancement

#231 Quick fix for icon example code minification bug.
  src/pages/components/icon.tsx
Labels: bug

#245 Upgrade dependencies and remove unnecessary console.log.
  src/pages/components/button.tsx
  yarn.lock
Labels: bug, dependencies

#256 Feature/update transifex texts
  locale/en/block.json
  locale/en/icon.json
  locale/fi/accessibility-statement.json
  locale/fi/block.json
  locale/fi/breadcrumb.json
  locale/fi/button.json
  locale/fi/colors.json
  locale/fi/common.json
  locale/fi/components.json
  locale/fi/designers.json
  locale/fi/dropdown.json
  locale/fi/expander.json
  locale/fi/heading.json
  locale/fi/home.json
  locale/fi/icon.json
  locale/fi/info.json
  locale/fi/link.json
  locale/fi/searchinput.json
  locale/fi/styles.json
  locale/fi/text.json
  locale/fi/textinput.json
  locale/fi/toggle.json
  locale/fi/typography.json
Labels: bug, enhancement

#260 Upgrade dependencies
  yarn.lock
Labels: dependencies

#261 Update suomifi-ui-components dependency version to 0.8.0
  locale/af/block.json
  locale/af/colors.json
  locale/en/colors.json
  locale/fi/colors.json
  package.json
  src/components/Annotation.tsx
  src/components/BypassLink.tsx
  src/components/ComponentDescription.tsx
  src/components/ContentBoxes.tsx
  src/components/Footer.tsx
  src/components/Hero.tsx
  src/components/MainContent.tsx
  src/components/MainMenu.tsx
  src/components/MainMenuItem.tsx
  src/components/MobileDevice.tsx
  src/components/NavItem.tsx
  src/components/Navigation.tsx
  src/components/NoteBox.tsx
  src/components/NotificationBox.tsx
  src/components/SideNav.tsx
  src/components/SideNavItem.tsx
  src/components/header.tsx
  src/examples/customTheme.js
  src/pages/styles/colors.tsx
  src/pages/styles/icons.tsx
  src/pages/styles/typography.tsx
  yarn.lock
Labels: dependencies

#275 Update suomifi-ui-components dependency to 0.9.0
  package.json
  yarn.lock
Labels: dependencies

#276 [Feature] TextInput documentation update
  locale/af/textinput.json
  locale/en/textinput.json
  locale/fi/textinput.json
  src/pages/components/textinput.tsx
Labels: enhancement

#277 [Feature]Add language menu component page
  .tx/config
  locale/af/languagemenu.json
  locale/en/languagemenu.json
  locale/fi/languagemenu.json
  src/components/ExampleComponents.tsx
  src/config/sidenav/components.js
  src/pages/components/languagemenu.tsx
Labels: enhancement

#278 Release version 0.1.2
  package.json
Labels: release

#293 [Enhancement] Enhance icon component page accessibility
  locale/af/icon.json
  locale/en/icon.json
  locale/fi/icon.json
  src/pages/components/icon.tsx
Labels: enhancement

#305 [Fix]Adds missing translation content & structure
  locale/af/designers.json
  locale/en/designers.json
  locale/fi/accessibility.json
  locale/fi/designers.json
  locale/fi/info.json
Labels: bug

#307 [Feature] Upgrade the dependencies
  yarn.lock
Labels: dependencies

#312 [Feature] Added the disclaimer text for accessibility
  locale/fi/home.json
Labels: enhancement

#310 [Feature] Update logo on the header
  locale/af/common.json
  locale/en/common.json
  locale/fi/common.json
  src/components/header.tsx
  src/staticIcons/designSystemLogo.svg
Labels: enhancement

#311 [Feature] Change alpha-texts to beta
  locale/en/common.json
  locale/fi/common.json
  locale/fi/home.json
Labels: enhancement
