Repository vrk-kpa/suomifi-design-system, pull requests merged in 2021-04, with the labels that each got.

#512 [Fix] Update and remove content to bring site more up to date
  locale/af/common.json
  locale/af/home.json
  locale/en/common.json
  locale/en/home.json
  locale/fi/common.json
  locale/fi/components.json
  locale/fi/designers.json
  locale/fi/home.json
  locale/fi/info.json
  locale/fi/styles.json
  src/components/Footer.tsx
  src/components/utils/outline.ts
Labels: enhancement

#513 [Feature] Update suomifi dependencies
  package.json
  src/components/Annotation.tsx
  src/components/ComponentDescription.tsx
  src/components/ContentBoxes.tsx
  src/components/ExampleComponents.tsx
  src/components/Hero.tsx
  src/components/NoteBox.tsx
  src/components/Section.tsx
  src/pages/404.tsx
  src/pages/components/block.tsx
  src/pages/components/breadcrumb.tsx
  src/pages/components/button.tsx
  src/pages/components/checkbox.tsx
  src/pages/components/dropdown.tsx
  src/pages/components/expander.tsx
  src/pages/components/heading.tsx
  src/pages/components/icon.tsx
  src/pages/components/index.tsx
  src/pages/components/languagemenu.tsx
  src/pages/components/link.tsx
  src/pages/components/radiobutton.tsx
  src/pages/components/searchinput.tsx
  src/pages/components/text.tsx
  src/pages/components/textarea.tsx
  src/pages/components/textinput.tsx
  src/pages/components/toggle.tsx
  src/pages/info/accessibility.tsx
  src/pages/info/designers.tsx
  src/pages/info/developers.tsx
  src/pages/info/index.tsx
  src/pages/styles/colors.tsx
  src/pages/styles/icons.tsx
  src/pages/styles/index.tsx
  src/pages/styles/typography.tsx
  yarn.lock
Labels: dependencies

#518 [Feature] Combobox component page
  .tx/config
  locale/af/multiselect.json
  locale/en/checkbox.json
  locale/en/multiselect.json
  locale/fi/multiselect.json
  src/config/sidenav/components.js
  src/pages/components/multiselect.tsx
Labels: enhancement

#520 [Fix] Component code example display names and hide combobox
  locale/af/button.json
  locale/af/toggle.json
  locale/en/button.json
  locale/en/toggle.json
  locale/fi/button.json
  locale/fi/dropdown.json
  locale/fi/textarea.json
  locale/fi/toggle.json
  src/config/sidenav/components.js
  src/pages/components/button.tsx
  src/pages/components/dropdown.tsx
  src/pages/components/expander.tsx
  src/pages/components/link.tsx
  src/pages/components/multiselect.tsx
  src/pages/components/radiobutton.tsx
Labels: bug

#521 [Release] 1.0.0
  package.json
Labels: release
